name: Build jar file

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk18

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize the project and build the jar file
        run: |
          ./do.sh init
      - name: Archive jar file
        uses: actions/upload-artifact@v3
        with:
          name: Synthesizer
          path: |
            build/libs/*jar
            !build/libs/*-sources.jar
